### ISSUE TITLE
Couldn't find bernouilliGamma.statistics function for downscaling precipitation 

### ISSUE THREAD

**Issue by matiaseolmo** [SantanderMetGroup/downscaleR.keras#1]
Hello!
I'm trying to reproduce the example of:
https://github.com/SantanderMetGroup/DeepDownscaling/blob/master/2020_Bano_GMD_FULL.ipynb
for downscaling precipitation, but it seems the function bernoulliGamma.statistics for some reason does not appear when loading downscaleR.keras, returning the following message:
Error in bernouilliGamma.statistics(p = subsetGrid(pred, var = "precip1"),  : 
  could not find function "bernouilliGamma.statistics"
I can't find the code for the function either, maybe something is missing within the package?
Thanks!
Matías

**Comment by jorgebanomedina** [comment]
Hi Matias,

That function is deprecated in the master branch. To reproduce the results please make sure to install the appropriate versions of the C4R libraries. In particular, for downscaleR.keras the version is 0.0.2. You can do that by typing:

devtools::install_github(“SantanderMetGroup/downscaleR.keras@v0.0.2”)

There is also a conda installation available (v1.3.0) that contains the exact versions of the C4R libraries to fully reproduce the notebook.

Let me know if it works.

Cheers

Jorge

**Comment by matiaseolmo** [comment]
Thanks, Jorge!
I didn't realise that. It's perfectly working now.
Cheers,
Matías
